# LESSON 1
## NumPy Array and Vectorization

NumPy is a library that has ndarray as its basic data structure used to handle arrays and matrices

In [1]:
# Convention for Importing Numpy 

import numpy as np

In [4]:
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [8]:
a = np.array(arr)
print("The value of a is ", a)
print(type(a))
print(a.shape)
print(a.dtype)

# get the dimension of a with ndim
print("The dimension of a is ", a.ndim)

The value of a is  [6 7 8 9]
<class 'numpy.ndarray'>
(4,)
int32
The dimension of a is  1


In [12]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print("The value of b is ", b)
"The dimension of b is ", b.ndim
"The shape of b is ", b.shape

The value of b is  [[1 2 3]
 [4 5 6]]


('The shape of b is ', (2, 3))

There are also some inbuilt functions that can be used to initialize numpy which include empty (), zeros (), ones (), full (), random.random()

In [26]:
# a 2X3 array of ramdom numbers
np.random.random((2,3))

array([[0.74368506, 0.24383767, 0.29817026],
       [0.24729545, 0.09040372, 0.7605856 ]])

In [27]:
# a 2X3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# a 2X3 array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.98807563e-321],
       [2.33419537e-312, 2.31297541e-312, 1.43870112e-311]])

In [154]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

TypeError: 'tuple' object cannot be interpreted as an integer

# Intra-operability of arrays and scalars

Vectorization in numpy arrays allows for faster processing by eliminating for loops when dealing with arrays of equal shape.

In [40]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

c + d
c*d
5/c
c**2
c**3

array([[729., 512., 343.],
       [  1.,   8.,  27.]])

# Indexing with arrays & using arrays for data processing


In [46]:
a[0] = 6
a[1] = 10
a[3] = 9
print (a)

[ 6 10  8  9]


In [44]:
b[0,0] = 1
print(b)

[[1 2 3]
 [4 5 6]]


Elements in arrays can also be retrieved by slicing rows and columns or a combination of indexing and slicing

In [54]:
e = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]])
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

There are other advanced methods of indexing which are shown below

In [52]:
# Integer indexing
e[[2, 0, 3, 1], [2, 1, 0, 2]]

array([18, 11, 19, 15])

In [59]:
# boolean indexing meeting a specific condition
e[e>15]

array([16, 17, 18, 19, 20, 21])

In [60]:
sum(e)

array([58, 62, 66])

# LESSON 3
# Pandas - So much more than a cute animal
Pandas is a library used for data manipulation and built on Numpy with other ways of indexing other than using integers


In [66]:
# Convention for importing pandas
import pandas as pd
days = pd.Series(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])
print(days)

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
dtype: object


In [108]:
# creating series with numpy array

days_list = np.array(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])
Pandas_days = pd.Series(days_list)
print(Pandas_days)

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
dtype: object


In [119]:
# Using strings as index
days = pd.Series(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], index = ['a', 'b', 'c', 'd', 'e'])
days

a       Monday
b      Tuesday
c    Wednesday
d     Thursday
e       Friday
dtype: object

In [117]:
# Creating series from a dictionary

days1 = pd.Series({'a': 'Monday', 'b': 'Tuesday', 'c': 'Wednesday', 'd': 'Thursday', 'e': 'Friday'})
days1

a       Monday
b      Tuesday
c    Wednesday
d     Thursday
e       Friday
dtype: object

Series can be accessed using the specified index as shown below

In [122]:
days[0]
days[2:]

c    Wednesday
d     Thursday
e       Friday
dtype: object

A DataFrame can be described as a table (2 dimensions) made up of many series with the same index. It holds data in rows and columns just like a spreadsheet. Series, dictionaries, lists other dataframes and numpy arrays can be used to create new ones. 

In [128]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [131]:
# Create a dataframe from dictionary
df_dict = {'Country': ['Ghana', 'Kenya', 'Nigeria', 'Togo'], 
           'Capital': ['Acra', 'Nairobi', 'Abuja', 'Lome'], 
           'Population': [10000, 8500, 35000, 12000],
           'Age': [60, 70, 80, 75]
          }
df = pd.DataFrame(df_dict, index = [1, 2, 3, 4])
df



Country  Capital  Population  Age
1    Ghana     Acra       10000   60
2    Kenya  Nairobi        8500   70
3  Nigeria    Abuja       35000   80
4     Togo     Lome       12000   75

In [132]:
import numpy as np
np.random.seed(40)
np.random.random((2,3))

array([[0.40768703, 0.05536604, 0.78853488],
       [0.28730518, 0.45035059, 0.30391231]])

# LESSON 4
## Data Types and Data Wrangling
The pandas library is vast enough to read data from and save to several file formats such as CSV, JSON, HTML and even databases
Pandas can connect to databases, get data with queries and save in a dataframe



In [146]:
url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv'
Fuel_Data = pd.read_csv(url, error_bad_lines = False)
Fuel_Data

record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
29518    neil simpson ct #1                 gas       mcf          18799.0   
29519  cheyenne prairie 58%                 gas       mcf         806730.0   
29520     lange ct facility                 gas       mcf         104554.0   
29521       wygen 3 bhp 52%                coal       ton         315945.0   
29522       wygen 3 bhp 52%                 gas       mcf          17853.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                   16.590                      18.59   
1                   16.592                      18.58   
2                   24.130                      39.72   
3                   23.950                      47.21   
4                    1.000                       2.77   
...                    ...                        ...   
29518                1.059                       4.78   
29519                1.050                       3.65   
29520                1.060                       4.77   
29521               16.108                       3.06   
29522                1.059                       0.00   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                             18.53                1.121  
1                             18.53                1.120  
2                             38.12                1.650  
3                             45.99                1.970  
4                              2.77                2.570  
...                             ...                  ...  
29518                          4.78                9.030  
29519                          3.65                6.950  
29520                          4.77                8.990  
29521                         14.76                1.110  
29522                          0.00               11.680  

[29523 rows x 11 columns]

In [147]:
Fuel_Data.describe(include = 'all')

record_id  utility_id_ferc1   report_year  \
count                     29523      29523.000000  29523.000000   
unique                    29523               NaN           NaN   
top     f1_fuel_2000_12_143_1_9               NaN           NaN   
freq                          1               NaN           NaN   
mean                        NaN        118.601836   2005.806050   
std                         NaN         74.178353      7.025483   
min                         NaN          1.000000   1994.000000   
25%                         NaN         55.000000   2000.000000   
50%                         NaN        122.000000   2006.000000   
75%                         NaN        176.000000   2012.000000   
max                         NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

In [148]:
Fuel_Data.shape

(29523, 11)

In [149]:
# Check for missing Data
Fuel_Data.isnull().sum()


record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [150]:
# use groupby to count the sum of each unique value in the fuel Unit column
Fuel_Data.groupby('fuel_unit')['fuel_unit'].count()

fuel_unit
bbl        7998
gal          84
gramsU      464
kgU         110
mcf       11354
mmbtu       180
mwdth        95
mwhth       100
ton        8958
Name: fuel_unit, dtype: int64

In [151]:
# fill the missing data with mcf which has the highest number of instance
Fuel_Data[['fuel_unit']] = Fuel_Data[['fuel_unit']].fillna(value = 'mcf')

In [152]:
# Check if the missing Data have being filled
Fuel_Data.isnull().sum()

record_id                       0
utility_id_ferc1                0
report_year                     0
plant_name_ferc1                0
fuel_type_code_pudl             0
fuel_unit                       0
fuel_qty_burned                 0
fuel_mmbtu_per_unit             0
fuel_cost_per_unit_burned       0
fuel_cost_per_unit_delivered    0
fuel_cost_per_mmbtu             0
dtype: int64

In [157]:
Fuel_Data.groupby('report_year')['report_year'].count()

report_year
1994    1235
1995    1201
1996    1088
1997    1094
1998    1107
1999    1050
2000    1373
2001    1356
2002    1205
2003    1211
2004    1192
2005    1269
2006    1243
2007    1264
2008    1228
2009    1222
2010    1261
2011    1240
2012    1243
2013    1199
2014    1171
2015    1093
2016    1034
2017     993
2018     951
Name: report_year, dtype: int64

In [159]:
Fuel_Data.groupby('fuel_type_code_pudl')['fuel_type_code_pudl'].count()

fuel_type_code_pudl
coal        8547
gas        11486
nuclear      818
oil         8064
other        167
waste        441
Name: fuel_type_code_pudl, dtype: int64

In [158]:
Fuel_Data.groupby('fuel_type_code_pudl').first()

record_id  utility_id_ferc1  report_year  \
fuel_type_code_pudl                                                          
coal                  f1_fuel_1994_12_1_0_7                 1         1994   
gas                  f1_fuel_1994_12_2_0_10                 2         1994   
nuclear               f1_fuel_1994_12_2_1_1                 2         1994   
oil                   f1_fuel_1994_12_6_0_2                 6         1994   
other                f1_fuel_1994_12_11_0_6                11         1994   
waste                 f1_fuel_1994_12_9_0_3                 9         1994   

                     plant_name_ferc1 fuel_unit  fuel_qty_burned  \
fuel_type_code_pudl                                                
coal                         rockport       ton        5377489.0   
gas                         chickasaw       mcf          40533.0   
nuclear              joseph m. farley       kgU           2260.0   
oil                      clinch river       bbl           6510.0   
other                      w.f. wyman       bbl          55652.0   
waste                    b.l. england       ton           2438.0   

                     fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
fuel_type_code_pudl                                                   
coal                           16.590000                     18.590   
gas                             1.000000                      2.770   
nuclear                         0.064094                     28.770   
oil                             5.875338                     32.130   
other                           0.149719                     14.685   
waste                           0.015939                     34.180   

                     fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
fuel_type_code_pudl                                                     
coal                                       18.530                1.121  
gas                                         2.770                2.570  
nuclear                                     0.000                0.450  
oil                                        23.444                5.469  
other                                      15.090                2.335  
waste                                      34.180                1.072

In [160]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import csv